name: "deploy-to-sap-btp-with-ctms"
description: "GitHub Action to deploy application archives (MTAR files) to SAP BTP via SAP Cloud Transport Management Service (CTMS)"
author: "Mauricio Lauffer"

inputs:
  CTMS_TOKEN_SERVICE_URL:
    description: "Value of url (within the uaa section) from the service key of your CTMS instance."
    required: true
  CTMS_CLIENT_ID:
    description: "Value of clientid from the service key of your CTMS instance."
    required: true
  CTMS_CLIENT_SECRET:
    description: "Value of clientsecret (within the uaa section) from the service key."
    required: true
  CTMS_API_URL:
    description: "Value of uri from the service key of your CTMS instance."
    required: true
  CTMS_NODE_NAME:
    description: "The name of the target Transport Node in CTMS where the archive should be imported"
    required: true
  CTMS_FILE_PATH:
    description: "Path within the runner's workspace to the application archive file (e.g., app.mtar, my-app.zip)"
    required: true
  CTMS_TR_DESCRIPTION:
    description: "Description for the transport request created in CTMS"
    required: true
  CTMS_TR_CONTENT_TYPE:
    description: "Content type of the archive. Must be one of: MTA, XSCDU, APP"
    required: true
  CTMS_TR_STORAGE_TYPE:
    description: "Storage type for the transport request. Must be one of: FILE, REFERENCE. Typically FILE for direct uploads"
    required: true
  CTMS_TR_USER_NAME:
    description: "Optional user name displayed in the Cloud Transport Management UI. If omitted, the authentication user may be shown."
    required: false

outputs:
  CTMS_NODE_ID:
    description: "ID of Transport Node where content was put in"
  CTMS_NODE_NAME:
    description: "Name of Transport Node where content was put in"
  CTMS_QUEUE_ID:
    description: "ID of Import Queue of the Transport Node"

branding:
  icon: "truck"
  color: "blue"

runs:
  using: "node20"
  main: "dist/index.js"
